apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: JaxDemo
  description: "demo of backstage"
  labels:
    example.com/custom: custom_label_value
  annotations:
    github.com/project-slug: themarek/backstageJaxDemo2023
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: folder-name/job-name
  tags:
    - java
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard    
    - url: https://slack.com
      title: Developer Chat
      icon: chat
      type: admin-dashboard          
spec:
  type: website
  lifecycle: experimental
  owner: "marek"
  system: "demo"
  providesApi:
    - API:default/JAXdemoAPI
  dependsOn:
    - API:default/JAXdemoAPI


---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: JAXdemoAPI
  description: jax demo api
  tags:
    - store
    - rest
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard    

spec:
  type: openapi
  lifecycle: experimental
  owner: marek  
  system: "demo"  
  definition: 
    $text: ./openapi.yaml