openapi: 3.0.3
info:
  version: 1.0.0
  title: Documentation Service
  description: A service that allows CRUD operations on documentation
  contact:
    name: Your Name
    email: your.email@example.com
paths:
  /documents:
    get:
      summary: Retrieve all documents
      operationId: getAllDocuments
      responses:
        '200':
          description: A list of all documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
    post:
      summary: Create a new document
      operationId: createDocument
      requestBody:
        description: The document to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentInput'
      responses:
        '201':
          description: The created document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
  /documents/{id}:
    parameters:
      - name: id
        in: path
        description: The ID of the document to retrieve
        required: true
        schema:
          type: string
    get:
      summary: Retrieve a document by ID
      operationId: getDocumentById
      responses:
        '200':
          description: The requested document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
    put:
      summary: Update a document
      operationId: updateDocument
      parameters:
        - name: id
          in: path
          description: The ID of the document to update
          required: true
          schema:
            type: string
      requestBody:
        description: The document to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentInput'
      responses:
        '200':
          description: The updated document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '404':
          description: Document not found
    delete:
      summary: Delete a document
      operationId: deleteDocument
      parameters:
        - name: id
          in: path
          description: The ID of the document to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Document deleted
        '404':
          description: Document not found
components:
  schemas:
    Document:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
    DocumentInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content
